### ISSUE TITLE
User documentation 8.1

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#12]
Admin section 8.1 is very incomplete. More explanations are needed to explain it to the user. It should be possible to read this section and not the rest of the documentation

**Comment by PRUBHTEJ** [comment]
The descriptions for Graph store endpoint, Default graph, Graph prefix and thread pool size are missing. I was unable to find anything related to them on the internet. Though, I'll try once again.

**Comment by PRUBHTEJ** [comment]
1. For Graph Store Protocol: 
https://www.w3.org/TR/2013/REC-sparql11-http-rdf-update-20130321/
2. Default Graph: Did not find anything for that.
3. Graph Prefix: Did not find anything for that.
4. Thread pool size: 
https://engineering.zalando.com/posts/2019/04/how-to-set-an-ideal-thread-pool-size.html 
(Though, I'm not sure if this one's apt).

**Comment by cjmyers** [comment]
The graph store endpoint is the endpoint for the triplestore database where the data is stored.  In this case, it is the endpoint for virtuoso.

The default graph is the URI prefix for the public graph in the database.

The graph prefix is the URI prefix for all graphs in the database.

The thread pool size is the number of threads that virtuoso is allowed to use.

**Comment by PRUBHTEJ** [comment]
I'll add these definitions to the docs.

**Comment by PRUBHTEJ** [comment]
I've added these definitions to the admin section. Kindly have a look.
