### ISSUE TITLE
8.6 user docs clarify

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#15]
You need to explain when adding a registry is this adding a specific registry to your own instance or is it applying to have your instance added to the registry. If it is the first then an explanation of how to add your instance to the web of registries is needed.

**Comment by PRUBHTEJ** [comment]
Agreed, that is a bit confusing. To clear out that confusion, I've added a sentence at the end of point 2, section 8.6, which is as follows:
**This will add an already existing registry of SynBioHub, to the list of registries on you SynBioHub local instance.**

**Comment by JMante1** [comment]
I like it. Just change you to your and you can close the issue.

**Comment by PRUBHTEJ** [comment]
Done the required changes.

**Comment by PRUBHTEJ** [comment]
Closing the issue
