### ISSUE TITLE
User doc 1.3 Advanced search clarify

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#17]
The description of Modified After Modified Before is not clear

**Comment by PRUBHTEJ** [comment]
For this, I'm also not sure what it exactly means but a rough definition can be included as follows: Any changes to a particular record in any form by any particular user. Is this correct?

**Comment by JMante1** [comment]
@cjmyers what do you think? Do you have a clearer definition to use?

**Comment by cjmyers** [comment]
The timeframe between the record may had been modified. 

Change to:

The timeframe in which the record was last modified.

---
Also,

the timeframe between which the record was created. 

Change to:

The timeframe in which the record was created.

**Comment by PRUBHTEJ** [comment]
I've Modified these. Kindly check

**Comment by JMante1** [comment]
Make sure that for created the "The" is capitalised

**Comment by PRUBHTEJ** [comment]
Done that. Kindly have a look.
