### ISSUE TITLE
user doc 1.4 placement of sparql link

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#18]
The placement of the sparql link in the first sentence is odd as I expected to be taken to the synbiohub.org sparql search place. Please integrate the link elsewhere into the description

**Comment by PRUBHTEJ** [comment]
The first button directs to the page explaining syntactical complexities of SPARQL and what I'll do is to make the second one, i.e the **SPARQL page** to direct the user to the SPARQL page of SynBioHub.

But again, we have one issue, which might come into picture. We want to make the docs general for the global as well as the local instance, so this might hamper our goal.

**Comment by JMante1** [comment]
Could you instead link out to the syntactical complexities with the phrase "SPARQL is a query language". That makes it clearer that you are going to the sparql syntax page. I see your point about not wanting to go to synbiohub.org/sparql.

**Comment by PRUBHTEJ** [comment]
Addressed this issue. Kindly have a look.

**Comment by PRUBHTEJ** [comment]
@JMante1 
Kindly have a look.

**Comment by PRUBHTEJ** [comment]
@JMante1 Please have a look.

**Comment by JMante1** [comment]
Can you make the link reference "SPARQL is a query language" rather than just SPARQL

**Comment by PRUBHTEJ** [comment]
Addressed this issue.
