### ISSUE TITLE
URI Explanation

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#20]
The uri is mentioned a lot in the documentation but it is not fully clear what it is. Explaining that it is similar to a doi would be helpful. A definition should be given where uri is mentioned.

**Comment by PRUBHTEJ** [comment]
Rather than explaining, what we can do is to give a brief explanation in the glossary that we're planning to insert in the docs.

**Comment by JMante1** [comment]
I like that idea, and then the term uri could be made into a link to uri in the glossary.

**Comment by PRUBHTEJ** [comment]
I think, I've done the required changes.
