### ISSUE TITLE
Contact section

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#23]
with synbiohub list

**Comment by PRUBHTEJ** [comment]
Shouldn't this be merged with the **Report an Error** issue?
Also, during our weekly meeting Prof. @cjmyers had opened an issue about creating a reporting an error section, but I'm unable to find that. That issue contained information about the various points that could possibly be included in this section.

**Comment by cjmyers** [comment]
Maybe we can use child menu options for this too.  Maybe we could have sectioning as follows:

Contacts
-  Mailing Lists
-  Report an Issue

**Comment by JMante1** [comment]
I think you are looking for issue #4

**Comment by PRUBHTEJ** [comment]
So the section be renamed as Contact and then we have 2 child pages as **Contacts** and **Report an Issue**?

**Comment by cjmyers** [comment]
Not quite, section title is Contacts with 2 child pages, "Mailing Lists" and "Report an Issue"

**Comment by PRUBHTEJ** [comment]
Addressed this issue, Kindly have a look

**Comment by JMante1** [comment]
I like the report an issue section but to make it easier to find I would name the top level "Reporting issues and Contact". Additionally, for the mailing lists can you make the SynBioHub developer, SynBioHub user, SynBioHub plugins bold to make it easier to quickly scan?

**Comment by PRUBHTEJ** [comment]
I've made these keywords bold. But changing the name of the section, won't be a lot of help since we have child pages which'll appear once the user will click on the section heading.

**Comment by cjmyers** [comment]
Please move this sentence to end of section:

Note: For enhancements there are contact details in the “questions and contact” section.

and change to read:

Note: For questions, please use the mailing lists linked here <add link to Mailing List section>.

**Comment by JMante1** [comment]
Chris and I discussed this during my meeting today and came up with the section name "Questions and Issues" rather than 
 "Contact".

**Comment by PRUBHTEJ** [comment]
I've done the required changes .
