### ISSUE TITLE
About synbiohub section

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#24]
In the about synbiohub section. Add that parts can not only be stored and published but also shared.

**Comment by PRUBHTEJ** [comment]
Done that.

**Comment by JMante1** [comment]
You have added that they can be searched for and shared but now the storing and publishing is gone. I would put it like: 

SynBioHub provides computational access for software and data integration, and a graphical user interface that enables users to search for, store, share, and publish designs in a Web browser.

**Comment by PRUBHTEJ** [comment]
I've replaced this statement, with the one that you've mentioned.

**Comment by PRUBHTEJ** [comment]
Kindly have a look.
