### ISSUE TITLE
Add additional contributors

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub.github.io#26]
Yourself
Jeanet Mante
Eric Yu
Michael Zhang
Benjamin Hatch

https://myersresearchgroup.github.io/author/jet-mante/

**Comment by PRUBHTEJ** [comment]
Should I re-arrange this on the basis of alphabetical order ?

**Comment by cjmyers** [comment]
Sure.

**Comment by PRUBHTEJ** [comment]
I've added the additional contributors and a few corresponding links for each of them from the internet, though I'm not sure if they're all correct.
The format, which you'd explained during the meeting, Prof. @cjmyers isn't working so once they're up and running I'll edit those.

**Comment by cjmyers** [comment]
Looks good
