### ISSUE TITLE
Installation section: General

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#27]
It says this registry which is odd as it is not in a registry anymore. Additionally it is helpful if the stop is explained, what does it stop - is the setup parameters cleared. Also how do you restart once stopped? Finally, note that on windows need admin permissions to run docker - this should be called out.

**Comment by PRUBHTEJ** [comment]
1. Where is the word "registry", in this section?
2. As for the stop, yes I'll try to explain this.
3. For the docker, this shall be included in the docker docs, the link for which has already been included.

**Comment by JMante1** [comment]
1. Sorry meant this repository
3. Whilst it is included in docker docs it should also just be mentioned on the synbiohub docs as it is an important point to note and cause a lot of issues to inexperienced users if they don't find it in the documentation.

**Comment by PRUBHTEJ** [comment]
1. So initially we need to **git clone** the synbiohub-docker repo and then only we can have a local instance of SynBioHub.
2. OK, I'll put a NOTE  regarding docker on Windows.

**Comment by JMante1** [comment]
1. I think just changing this repository to this (LINK: https://github.com/SynBioHub/synbiohub-docker) should fix the oddness.
2. I would add to step two in the documentation (for Windows make sure you open the command terminal as an administrator). And for the docker bullet For Windows OS, click here. Add: "After installation make sure to run docker desktop as an administrator before moving to step two).

**Comment by PRUBHTEJ** [comment]
I've done the needful. Kindly have a look
