### ISSUE TITLE
Troubleshooting section needs to be developed

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#30]
it is currently blank

**Comment by cjmyers** [comment]
Let's remove it and with a new Report an Issue section.

**Comment by PRUBHTEJ** [comment]
That'll be done!

**Comment by PRUBHTEJ** [comment]
I've renamed the section to "Report an Error", but I'm unable to find the content that'll go in that section.

**Comment by cjmyers** [comment]
See issue #4

**Comment by PRUBHTEJ** [comment]
I think this needs to be closed.
