### ISSUE TITLE
References section

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#31]
Maybe call it publications or references and publications instead?

**Comment by PRUBHTEJ** [comment]
The section name earlier was "Further References"and upon discussions with prof. @cjmyers , it was changed to "References".

**Comment by PRUBHTEJ** [comment]
I'm fine by either!

**Comment by JMante1** [comment]
I would prefer "Publications" but it is up to @cjmyers

**Comment by cjmyers** [comment]
I think References is the more typical term.

**Comment by PRUBHTEJ** [comment]
So if reference is fine, then should this issue be closed?
