### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#32]
The documentation starts with "This section contains instructions on how you can implement various operations ranging from registering onto SynBioHub to uploading your genetic designs on SynBioHub, by using the user interface of SynBioHub. The sub-sections are as follows:" the use of implement is odd here as a user doesn't implement anything.

**Comment by PRUBHTEJ** [comment]
What would be better according to you?
According to me, Implementation is the realisation of an application, or execution of a plan or an idea.

**Comment by cjmyers** [comment]
I agree, implementation is incorrect.  Maybe: replace with "perform"

**Comment by JMante1** [comment]
I agree with Chris that perform is better than implement as implement has the idea of realisation of a plan rather than just carrying out steps.

**Comment by PRUBHTEJ** [comment]
Replaced the word "Implemented" with "Perform". Kindly have a look.
