### ISSUE TITLE
Admin SPARQL section

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub.github.io#39]
Should clarify that this can be used by administrators to perform any SPARQL query or update. Administrators can select any graph to query or update.  Administrators can not only view data, but can also delete or insert data using the SPARQL language.  PLEASE BE EXTREMELY CAREFUL WHEN YOU USE THE UPDATE FEATURE AS YOU CAN CORRUPT THE DATASET.

**Comment by PRUBHTEJ** [comment]
Addressed this issue.

**Comment by cjmyers** [comment]
Remove this text:

"On the search results page, there is button labeled as SPARQL. Clicking on that button will direct you to the SPARQL page. Since, SPARQL is a query language, hence it’ll query Synbiohub’s databases for the designs that you’re looking for. On the SPARQL page, you can select the graph that is from private or public. Here, public means searching amongst the public submissions, that can be viewed by and private means, the ones that are your personal collections. "

Remove all text starting from:

"Following is an example that selects all sbol ... " and ending with the end of the example.  We don't need to put an example in this section.

**Comment by PRUBHTEJ** [comment]
Addressed this issue.

**Comment by cjmyers** [comment]
Please change:
"a list of records matching with SPARQL query shall be displayed."

"the results of your request shall be displayed below the query box."

**Comment by PRUBHTEJ** [comment]
I've done these changes. Kindly have a look.

**Comment by cjmyers** [comment]
Looks good
