### ISSUE TITLE
Create a view section for each Top Level object type that you have an example for

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub.github.io#41]
Component (Definition)
Sequence
Implementation
Activity
Plan
Agent

**Comment by PRUBHTEJ** [comment]
Is there any specific order that I should put them in or the order which you've written in the comment above is fine, Prof. @cjmyers ?
Also, for the records which have the same details as that mentioned in the general section, what can be done?

**Comment by PRUBHTEJ** [comment]
1. On [this](https://synbiohub.org/public/igem/BBa_K1444010_sequence/1) page, I'm unable to understand the significance of **blast**, under the details section.
2. On the advanced search page, there is no object titles as implementation and plan. What can be done in this context?

For other sections, I've written the documentation. Kindly have a look.

**Comment by cjmyers** [comment]
For order, how about:
Collection
Module
Component
Sequence
Implementation
Activity
Agent
Plan

**Comment by cjmyers** [comment]
Blast is a type of sequence search, see:

https://blast.ncbi.nlm.nih.gov/Blast.cgi

**Comment by cjmyers** [comment]
If you cannot find any Implementation or Plan objects, you can skip these for now.

**Comment by PRUBHTEJ** [comment]
* Yes, I agree to the order and I've updated the viewing section --->Sequence sub-section, with further details.
* Yes, I was unable to find any implementation or plan objects.

**Comment by PRUBHTEJ** [comment]
Done that. Kindly have a look

**Comment by cjmyers** [comment]
Closing
