### ISSUE TITLE
Additional visualizations

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub.github.io#43]
Additional information be me rendered for record via visualization plugins.

**Comment by PRUBHTEJ** [comment]
Done the needful. Kindly have a look.

**Comment by cjmyers** [comment]
Additional information be me rendered for a record via visualization plugins.

->

Additional information may be rendered for a record via visualization plugins.

**Comment by PRUBHTEJ** [comment]
Addressed this issue. Kindly have a look.
