### ISSUE TITLE
Create documentation / demo video for setting up Benchling / ICE remotes

### ISSUE THREAD

**Issue by PRUBHTEJ** [SynBioHub/synbiohub.github.io#44]
Connecting remote instances is quite involved. Really need documentation and a demo video for this.

Some of the steps are:

Create a user on Benchling for the course.
Get API keys setup for this user by contacting Benchling.
Create an API key on Benchling for this new user.
Create a project/folder to link in transfers to/from SynBioHub.
Create an organization for this course.
Give this organization permission to read/write the SynBioHub transfer folder.
Create a remote on SynBioHub that uses this API key to access Benchling. You also need the folder id for the SynBioHub transfers. The folder id can be found on the settings.

**Comment by PRUBHTEJ** [comment]
The last we'd discussed this, @cjmyers was quite long ago. 
Is there anything we can do to include this in the remotes documentation?

**Comment by cjmyers** [comment]
This is probably not worth doing at this point.  Closing.
