### ISSUE TITLE
Check section header capitalization throughout

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub.github.io#49]
There are still a lot of sections/subsection headers that are not capitalized.  Please go through them all and make them consistent.

**Comment by cjmyers** [comment]
Ex. 2.1.2 Viewing a collection -> Viewing a Collection

**Comment by PRUBHTEJ** [comment]
Addressed this issue, @cjmyers.
Kindly have a look.
Used **https://capitalizemytitle.com** for the verification process.

**Comment by cjmyers** [comment]
Looks good.  Closing.
