### ISSUE TITLE
Suggestion - Glossary should be alphabetized

### ISSUE THREAD

**Issue by yu-eric** [SynBioHub/synbiohub.github.io#59]
This would make it easier to find the term you are looking for.

**Comment by PRUBHTEJ** [comment]
Sure, that can be done.
But, there are only a few terms explained as of now and this is an ever expanding section. I'm just waiting for a few more terms to be included in the glossary.

**Comment by PRUBHTEJ** [comment]
@JMante1 
What's your take?

**Comment by cjmyers** [comment]
I agree
