### ISSUE TITLE
User Documentation 2.2

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#6]
The explanation of image in the table is a definition of an image not the type of image presented by synbiohub when downloading.

**Comment by PRUBHTEJ** [comment]
Just for reference, I was trying to download the image of [this](https://synbiohub.org/public/bsu/module_BO_10845_bindsto_BO_3533/1) module, but I think that this is broken.

**Comment by JMante1** [comment]
Yes, it is broken. Try this link instead: https://synbiohub.org/public/bsu/module_BO_30843_encodes_BO_11239/1

I think it should allow you to download the visbol when you download image

**Comment by PRUBHTEJ** [comment]
As of now, it is still not working. What could be the possible issue?

**Comment by JMante1** [comment]
That is an issue with synbiohub. I have logged it here: https://github.com/SynBioHub/synbiohub/issues/1393

**Comment by PRUBHTEJ** [comment]
So what should be the definition?

**Comment by JMante1** [comment]
Image is a capture of the Visbol display at the top of the page.

**Comment by PRUBHTEJ** [comment]
Okay.
I've done the required changes.
