### ISSUE TITLE
Clean up formatting on the plugins page

### ISSUE THREAD

**Issue by yu-eric** [SynBioHub/synbiohub.github.io#62]
For example, the steps for Dockerizing a container has many commands that can be formatted in the red-coding font that has been done in other sections.

**Comment by PRUBHTEJ** [comment]
Think you're talking about taking about [dockerizing a plugin](https://wiki.synbiohub.org/plugins/#8-dockerising).

**Comment by PRUBHTEJ** [comment]
@yu-eric
Am I right about the reference you're making?
