### ISSUE TITLE
Suggestion: Update/Modify or delete the Read more box at the end of each page

### ISSUE THREAD

**Issue by LukasBuecherl** [SynBioHub/synbiohub.github.io#63]
At the end of each page is a blue box labeled read more. So far, it is only pointing at the next entry of the documentation. For example, if you are in the User Documentation, you have six points from searching for information to administration. 

The blue box below references to point 1 (Searching for information) as well. It is redundant and a little bit confusing. Maybe it can always point to the about SynBioHub page.

**Comment by PRUBHTEJ** [comment]
We already had a discussion regarding this in the developmental days, regarding the blue box and we'd decided to keep this to just have an easier navigation. Still, if Prof. @cjmyers says, this can removed.

**Comment by cjmyers** [comment]
I'm open to removing it, if it is confusing.

**Comment by PRUBHTEJ** [comment]
I also think, that it might be confusing for some. 
Should I remove it then?

**Comment by LukasBuecherl** [comment]
I think it should either display more information or just give a link to the about SynBioHub webpage. If that is seen as unnecessary, I think it should be deleted.

**Comment by PRUBHTEJ** [comment]
Customisability of this box, is pretty less. It's like either have whatever it has or let it go.

**Comment by cjmyers** [comment]
We can turn it off.  Can you carefully document how you turn it on/off in case we change our mind later?  Thanks.

**Comment by PRUBHTEJ** [comment]
I'll do that. For this kind of extra add-ons to the documentation, I'll make an additional section titled **Notes** in the Readme of synbiohub-docs. Would that suffice?

**Comment by cjmyers** [comment]
Yes that works

**Comment by PRUBHTEJ** [comment]
Ok, I'll do that.

**Comment by PRUBHTEJ** [comment]
I've done the required changes kindly have a look.

**Comment by PRUBHTEJ** [comment]
Addressed the issue.
