### ISSUE TITLE
External link in the upper right hand corner is not working

### ISSUE THREAD

**Issue by LukasBuecherl** [SynBioHub/synbiohub.github.io#64]
There is a link in the upper right-hand corner of the webpage. It is shown as an orange box with a WiFi symbol in it. I am not sure where it should point to. The link opened is 

https://synbiohub.github.io/userdocumentation/.Permalink 

However, if I click the box, I get an error 404 page not found.

**Comment by PRUBHTEJ** [comment]
Issue #46 , was opened by @JMante1 in this regard

**Comment by PRUBHTEJ** [comment]
Closing...
