### ISSUE TITLE
Plugins: Format Titles 

### ISSUE THREAD

**Issue by LukasBuecherl** [SynBioHub/synbiohub.github.io#65]
It is a minor thing, but under Plugins, the first headline reads:

 _What are plugins?_

and after that the next one 

_Types of Plugins_

Plugins should either be capitalized all the time or never. Since the rest of the webpage uses capitalized, I suggest doing the same.

**Comment by PRUBHTEJ** [comment]
Though I've tried to solve quite a few of these capitalization issues, some are still left to be addressed. 
I'll address this as well, @LukasBuecherl
Thanks for pointing out.

**Comment by PRUBHTEJ** [comment]
Addressed all the capitalisation issues!
