### ISSUE TITLE
visualization plugins link only points to SeqViz

### ISSUE THREAD

**Issue by Fontanapink** [SynBioHub/synbiohub.github.io#67]
The visualization plugins link in https://synbiohub.github.io/userdocumentation/viewinganddownloadinginformation/ only points to https://github.com/SynBioHub/Plugin-Visual-Seqviz.

Should it be pointing to [ALL visualization plugins](https://synbiohub.github.io/synbiohub-docker/#plugins)? Or it is like this by design?

**Comment by PRUBHTEJ** [comment]
@JMante1 What do you think?

**Comment by JMante1** [comment]
It is like that by design. It is the example
