### ISSUE TITLE
Section Python Windows run command

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#68]
As pointed out by @cjmyers  Option 5 in section 2.2.3.1.2.2 should be:

In the Powershell, enter the follwing command: `$env:FLASK_APP = "app"` or in the command window: `set FLASK_APP=app`

**Comment by PRUBHTEJ** [comment]
Addressed this Issue!
@JMante1 
Kindly have a look.

**Comment by PRUBHTEJ** [comment]
Closing!
