### ISSUE TITLE
Separate Admin Tab

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#7]
I suggest that admin documentation be moved to a tab separate from user documentation

**Comment by PRUBHTEJ** [comment]
We can create a childpage under the user docs section titled, "Administration"

**Comment by PRUBHTEJ** [comment]
So, as per the discussion with prof. @cjmyers , I'll be making child pages for every major section under the user documentation, and it would be apt to change the title to, **Separate childpages for every major section under documentation**.

**Comment by PRUBHTEJ** [comment]
I've added the child pages, kindly have a look!

**Comment by cjmyers** [comment]
This looks good to me.

**Comment by JMante1** [comment]
It looks good, my one gripe is that when you enter a section e.g. Admin all the subsections are 8.x but when reading the child page headings they are just Admin, not 8. Admin. That makes navigation a bit more difficult.

**Comment by PRUBHTEJ** [comment]
I've taken care of the ordering and given proper numbering to each section. Kindly have a look.
