### ISSUE TITLE
Quick start

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#8]
There should be a paragraph somewhere to enable a 'quick start'. It could probably go under the about section. It should explain that the instance is already online, key terms you might need to understand and that you can also find out more by just exploring and browsing by yourself. The documentation is a lot to read in the entirety and understanding synbiohub without reading everything is difficult.

**Comment by PRUBHTEJ** [comment]
I agree to that.
The first page of the documentation, should consist of this section. 
What I see is that it should contain the following:
1. Basic intro the global instance.
2. Explanation to a few of the parameters that are on that page.
3. How can one Sign-up(We can link to registering section)
4. How to view a record(Link to the general section for viewing)
5. How to search?
6. How to update an existing collection.
7. How to get your own local synbiohub instance.
Something of this sort, like in single bullets?

**Comment by JMante1** [comment]
That sounds perfect.

**Comment by PRUBHTEJ** [comment]
I'll add this to the documentation before our meeting tomorrow.

**Comment by PRUBHTEJ** [comment]
I've added the quick start section on the home page. Kindly have a look.
