### ISSUE TITLE
User documentation: 4.1.1 Creating a new collection

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/synbiohub.github.io#9]
The handlers apart from default are all plugins and should not be listed.

**Comment by PRUBHTEJ** [comment]
What I've done is that I've replaced the listed option, with the following statement: 
 You also need to select a handler. Out of the four options provided, default is the only one that's not a plugin, the rest are plugins and can be found in the plugins section. 

I should probably give a link to the respective plugins section, right?

**Comment by JMante1** [comment]
I would instead say:
You also need to select a handler. By default only one option is provided but more handlers can be added via submit plugins (LINK).

**Comment by PRUBHTEJ** [comment]
Done that. Kindly have a look

**Comment by JMante1** [comment]
I don't see the update pushed?

**Comment by PRUBHTEJ** [comment]
Done that. Sorry for the trouble.
